let products = [
  {
    id: "rec43w3ipXvP28vog",
    title: "high-back bench",
    company: "ikea",
    image: "./images/item-1.jpeg",
    price: 9.99,
  },
  {
    id: "rec4f2RIftFCb7aHh",
    title: "albany table",
    company: "marcos",
    image: "./images/item-2.jpeg",
    price: 79.99,
  },
  {
    id: "rec8kkCmSiMkbkiko",
    title: "accent chair",
    company: "caressa",
    image: "./images/item-3.jpeg",
    price: 25.99,
  },
  {
    id: "recBohCqQsot4Q4II",
    title: "wooden table",
    company: "caressa",
    image: "./images/item-4.jpeg",
    price: 45.99,
  },
  {
    id: "recDG1JRZnbpRHpoy",
    title: "dining table",
    company: "caressa",
    image: "./images/item-5.jpeg",
    price: 6.99,
  },
  {
    id: "recNWGyP7kjFhSqw3",
    title: "sofa set",
    company: "liddy",
    image: "./images/item-6.jpeg",
    price: 69.99,
  },
  {
    id: "recZEougL5bbY4AEx",
    title: "modern bookshelf",
    company: "marcos",
    image: "./images/item-7.jpeg",
    price: 8.99,
  },
  {
    id: "recjMK1jgTb2ld7sv",
    title: "emperor bed",
    company: "liddy",
    image: "./images/item-8.jpeg",
    price: 21.99,
  },
  {
    id: "recmg2a1ctaEJNZhu",
    title: "utopia sofa",
    company: "marcos",
    image: "./images/item-9.jpeg",
    price: 39.95,
  },
  {
    id: "recvKMNR3YFw0bEt3",
    title: "center",
    company: "OmniFood",
    image: "./images/item-1.jpeg",
    price: 29.9,
  },
  {
    id: "recxaXFy5IW539sgM",
    title: " sectional",
    company: "ikea",
    image: "./images/item-2.jpeg",
    price: 10.9,
  },
  {
    id: "recyqtRglGNGtO4Q5",
    title: "sofa",
    company: "PizzaHut",
    image: "./images/item-3.jpeg",
    price: 9.9,
  },
  {
    id: "recyqtRglGNGtO4Q5",
    title: "ather",
    company: "War Food",
    image: "./images/item-4.jpeg",
    price: 2.99,
  },
  {
    id: "recyqtRglGNGtO4Q5",
    title: "leatofa",
    company: "liddy",
    image: "./images/item-5.jpeg",
    price: 9.99,
  },
  {
    id: "recyqtRglGNGtO4Q5",
    title: "leath",
    company: "Demon King",
    image: "./images/item-6.jpeg",
    price: 8.99,
  },
  {
    id: "recyqtRglGNGtO4Q5",
    title: "eathofa",
    company: "Robust",
    image: "./images/item-7.jpeg",
    price: 3.99,
  },
  {
    id: "recyqtRglGNGtO4Q5",
    title: "vampire",
    company: "strong",
    image: "./images/item-8.jpeg",
    price: 8.9,
  },
  {
    id: "recyqtRglGNGtO4Q5",
    title: "warrior cream",
    company: "Icewar",
    image: "./images/item-9.jpeg",
    price: 6.79,
  },
];
